// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewClickHouseClient creates a new instance of ClickHouseClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClickHouseClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClickHouseClient {
	mock := &ClickHouseClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClickHouseClient is an autogenerated mock type for the ClickHouseClient type
type ClickHouseClient struct {
	mock.Mock
}

type ClickHouseClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ClickHouseClient) EXPECT() *ClickHouseClient_Expecter {
	return &ClickHouseClient_Expecter{mock: &_m.Mock}
}

// ExecuteQueryWithStats provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) ExecuteQueryWithStats(ctx context.Context, conn *entity.CHConnection, query string) (*entity.QueryStats, error) {
	ret := _mock.Called(ctx, conn, query)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQueryWithStats")
	}

	var r0 *entity.QueryStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) (*entity.QueryStats, error)); ok {
		return returnFunc(ctx, conn, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) *entity.QueryStats); ok {
		r0 = returnFunc(ctx, conn, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.QueryStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection, string) error); ok {
		r1 = returnFunc(ctx, conn, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_ExecuteQueryWithStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQueryWithStats'
type ClickHouseClient_ExecuteQueryWithStats_Call struct {
	*mock.Call
}

// ExecuteQueryWithStats is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
//   - query string
func (_e *ClickHouseClient_Expecter) ExecuteQueryWithStats(ctx interface{}, conn interface{}, query interface{}) *ClickHouseClient_ExecuteQueryWithStats_Call {
	return &ClickHouseClient_ExecuteQueryWithStats_Call{Call: _e.mock.On("ExecuteQueryWithStats", ctx, conn, query)}
}

func (_c *ClickHouseClient_ExecuteQueryWithStats_Call) Run(run func(ctx context.Context, conn *entity.CHConnection, query string)) *ClickHouseClient_ExecuteQueryWithStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClickHouseClient_ExecuteQueryWithStats_Call) Return(queryStats *entity.QueryStats, err error) *ClickHouseClient_ExecuteQueryWithStats_Call {
	_c.Call.Return(queryStats, err)
	return _c
}

func (_c *ClickHouseClient_ExecuteQueryWithStats_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection, query string) (*entity.QueryStats, error)) *ClickHouseClient_ExecuteQueryWithStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreateSQL provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) GetCreateSQL(ctx context.Context, conn *entity.CHConnection, tableName string) (string, error) {
	ret := _mock.Called(ctx, conn, tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetCreateSQL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) (string, error)); ok {
		return returnFunc(ctx, conn, tableName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) string); ok {
		r0 = returnFunc(ctx, conn, tableName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection, string) error); ok {
		r1 = returnFunc(ctx, conn, tableName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_GetCreateSQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreateSQL'
type ClickHouseClient_GetCreateSQL_Call struct {
	*mock.Call
}

// GetCreateSQL is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
//   - tableName string
func (_e *ClickHouseClient_Expecter) GetCreateSQL(ctx interface{}, conn interface{}, tableName interface{}) *ClickHouseClient_GetCreateSQL_Call {
	return &ClickHouseClient_GetCreateSQL_Call{Call: _e.mock.On("GetCreateSQL", ctx, conn, tableName)}
}

func (_c *ClickHouseClient_GetCreateSQL_Call) Run(run func(ctx context.Context, conn *entity.CHConnection, tableName string)) *ClickHouseClient_GetCreateSQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClickHouseClient_GetCreateSQL_Call) Return(s string, err error) *ClickHouseClient_GetCreateSQL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ClickHouseClient_GetCreateSQL_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection, tableName string) (string, error)) *ClickHouseClient_GetCreateSQL_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabases provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) GetDatabases(ctx context.Context, conn *entity.CHConnection) ([]string, error) {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabases")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) ([]string, error)); ok {
		return returnFunc(ctx, conn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) []string); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection) error); ok {
		r1 = returnFunc(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_GetDatabases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabases'
type ClickHouseClient_GetDatabases_Call struct {
	*mock.Call
}

// GetDatabases is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ClickHouseClient_Expecter) GetDatabases(ctx interface{}, conn interface{}) *ClickHouseClient_GetDatabases_Call {
	return &ClickHouseClient_GetDatabases_Call{Call: _e.mock.On("GetDatabases", ctx, conn)}
}

func (_c *ClickHouseClient_GetDatabases_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ClickHouseClient_GetDatabases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClickHouseClient_GetDatabases_Call) Return(strings []string, err error) *ClickHouseClient_GetDatabases_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *ClickHouseClient_GetDatabases_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) ([]string, error)) *ClickHouseClient_GetDatabases_Call {
	_c.Call.Return(run)
	return _c
}

// GetSchema provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) GetSchema(ctx context.Context, conn *entity.CHConnection, tableName string) (*entity.TableSchema, error) {
	ret := _mock.Called(ctx, conn, tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetSchema")
	}

	var r0 *entity.TableSchema
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) (*entity.TableSchema, error)); ok {
		return returnFunc(ctx, conn, tableName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection, string) *entity.TableSchema); ok {
		r0 = returnFunc(ctx, conn, tableName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TableSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection, string) error); ok {
		r1 = returnFunc(ctx, conn, tableName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_GetSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSchema'
type ClickHouseClient_GetSchema_Call struct {
	*mock.Call
}

// GetSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
//   - tableName string
func (_e *ClickHouseClient_Expecter) GetSchema(ctx interface{}, conn interface{}, tableName interface{}) *ClickHouseClient_GetSchema_Call {
	return &ClickHouseClient_GetSchema_Call{Call: _e.mock.On("GetSchema", ctx, conn, tableName)}
}

func (_c *ClickHouseClient_GetSchema_Call) Run(run func(ctx context.Context, conn *entity.CHConnection, tableName string)) *ClickHouseClient_GetSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClickHouseClient_GetSchema_Call) Return(tableSchema *entity.TableSchema, err error) *ClickHouseClient_GetSchema_Call {
	_c.Call.Return(tableSchema, err)
	return _c
}

func (_c *ClickHouseClient_GetSchema_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection, tableName string) (*entity.TableSchema, error)) *ClickHouseClient_GetSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerInfo provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) GetServerInfo(ctx context.Context, conn *entity.CHConnection) (string, error) {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) (string, error)); ok {
		return returnFunc(ctx, conn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) string); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection) error); ok {
		r1 = returnFunc(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type ClickHouseClient_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ClickHouseClient_Expecter) GetServerInfo(ctx interface{}, conn interface{}) *ClickHouseClient_GetServerInfo_Call {
	return &ClickHouseClient_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx, conn)}
}

func (_c *ClickHouseClient_GetServerInfo_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ClickHouseClient_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClickHouseClient_GetServerInfo_Call) Return(s string, err error) *ClickHouseClient_GetServerInfo_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ClickHouseClient_GetServerInfo_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) (string, error)) *ClickHouseClient_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTables provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) GetTables(ctx context.Context, conn *entity.CHConnection) ([]entity.TableMeta, error) {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for GetTables")
	}

	var r0 []entity.TableMeta
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) ([]entity.TableMeta, error)); ok {
		return returnFunc(ctx, conn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) []entity.TableMeta); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TableMeta)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.CHConnection) error); ok {
		r1 = returnFunc(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClickHouseClient_GetTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTables'
type ClickHouseClient_GetTables_Call struct {
	*mock.Call
}

// GetTables is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ClickHouseClient_Expecter) GetTables(ctx interface{}, conn interface{}) *ClickHouseClient_GetTables_Call {
	return &ClickHouseClient_GetTables_Call{Call: _e.mock.On("GetTables", ctx, conn)}
}

func (_c *ClickHouseClient_GetTables_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ClickHouseClient_GetTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClickHouseClient_GetTables_Call) Return(tableMetas []entity.TableMeta, err error) *ClickHouseClient_GetTables_Call {
	_c.Call.Return(tableMetas, err)
	return _c
}

func (_c *ClickHouseClient_GetTables_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) ([]entity.TableMeta, error)) *ClickHouseClient_GetTables_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type ClickHouseClient
func (_mock *ClickHouseClient) Ping(ctx context.Context, conn *entity.CHConnection) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClickHouseClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type ClickHouseClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ClickHouseClient_Expecter) Ping(ctx interface{}, conn interface{}) *ClickHouseClient_Ping_Call {
	return &ClickHouseClient_Ping_Call{Call: _e.mock.On("Ping", ctx, conn)}
}

func (_c *ClickHouseClient_Ping_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ClickHouseClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClickHouseClient_Ping_Call) Return(err error) *ClickHouseClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClickHouseClient_Ping_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) error) *ClickHouseClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
