// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewConnectionRepository creates a new instance of ConnectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionRepository {
	mock := &ConnectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConnectionRepository is an autogenerated mock type for the ConnectionRepository type
type ConnectionRepository struct {
	mock.Mock
}

type ConnectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionRepository) EXPECT() *ConnectionRepository_Expecter {
	return &ConnectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ConnectionRepository
func (_mock *ConnectionRepository) Create(ctx context.Context, conn *entity.CHConnection) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConnectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ConnectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ConnectionRepository_Expecter) Create(ctx interface{}, conn interface{}) *ConnectionRepository_Create_Call {
	return &ConnectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, conn)}
}

func (_c *ConnectionRepository_Create_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ConnectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionRepository_Create_Call) Return(err error) *ConnectionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConnectionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) error) *ConnectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ConnectionRepository
func (_mock *ConnectionRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConnectionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ConnectionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ConnectionRepository_Expecter) Delete(ctx interface{}, id interface{}) *ConnectionRepository_Delete_Call {
	return &ConnectionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ConnectionRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *ConnectionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionRepository_Delete_Call) Return(err error) *ConnectionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConnectionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *ConnectionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type ConnectionRepository
func (_mock *ConnectionRepository) FindAll(ctx context.Context) ([]*entity.CHConnection, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*entity.CHConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.CHConnection, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.CHConnection); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.CHConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConnectionRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type ConnectionRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ConnectionRepository_Expecter) FindAll(ctx interface{}) *ConnectionRepository_FindAll_Call {
	return &ConnectionRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *ConnectionRepository_FindAll_Call) Run(run func(ctx context.Context)) *ConnectionRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConnectionRepository_FindAll_Call) Return(cHConnections []*entity.CHConnection, err error) *ConnectionRepository_FindAll_Call {
	_c.Call.Return(cHConnections, err)
	return _c
}

func (_c *ConnectionRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.CHConnection, error)) *ConnectionRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type ConnectionRepository
func (_mock *ConnectionRepository) FindByID(ctx context.Context, id int64) (*entity.CHConnection, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.CHConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.CHConnection, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.CHConnection); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CHConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConnectionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ConnectionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ConnectionRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ConnectionRepository_FindByID_Call {
	return &ConnectionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ConnectionRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *ConnectionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionRepository_FindByID_Call) Return(cHConnection *entity.CHConnection, err error) *ConnectionRepository_FindByID_Call {
	_c.Call.Return(cHConnection, err)
	return _c
}

func (_c *ConnectionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.CHConnection, error)) *ConnectionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ConnectionRepository
func (_mock *ConnectionRepository) Update(ctx context.Context, conn *entity.CHConnection) error {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.CHConnection) error); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConnectionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ConnectionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *entity.CHConnection
func (_e *ConnectionRepository_Expecter) Update(ctx interface{}, conn interface{}) *ConnectionRepository_Update_Call {
	return &ConnectionRepository_Update_Call{Call: _e.mock.On("Update", ctx, conn)}
}

func (_c *ConnectionRepository_Update_Call) Run(run func(ctx context.Context, conn *entity.CHConnection)) *ConnectionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.CHConnection
		if args[1] != nil {
			arg1 = args[1].(*entity.CHConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionRepository_Update_Call) Return(err error) *ConnectionRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConnectionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, conn *entity.CHConnection) error) *ConnectionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
