// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewFavoriteRepository creates a new instance of FavoriteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteRepository {
	mock := &FavoriteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FavoriteRepository is an autogenerated mock type for the FavoriteRepository type
type FavoriteRepository struct {
	mock.Mock
}

type FavoriteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteRepository) EXPECT() *FavoriteRepository_Expecter {
	return &FavoriteRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type FavoriteRepository
func (_mock *FavoriteRepository) Create(ctx context.Context, favorite *entity.FavoriteComparison) error {
	ret := _mock.Called(ctx, favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.FavoriteComparison) error); ok {
		r0 = returnFunc(ctx, favorite)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FavoriteRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FavoriteRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - favorite *entity.FavoriteComparison
func (_e *FavoriteRepository_Expecter) Create(ctx interface{}, favorite interface{}) *FavoriteRepository_Create_Call {
	return &FavoriteRepository_Create_Call{Call: _e.mock.On("Create", ctx, favorite)}
}

func (_c *FavoriteRepository_Create_Call) Run(run func(ctx context.Context, favorite *entity.FavoriteComparison)) *FavoriteRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.FavoriteComparison
		if args[1] != nil {
			arg1 = args[1].(*entity.FavoriteComparison)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FavoriteRepository_Create_Call) Return(err error) *FavoriteRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FavoriteRepository_Create_Call) RunAndReturn(run func(ctx context.Context, favorite *entity.FavoriteComparison) error) *FavoriteRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type FavoriteRepository
func (_mock *FavoriteRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FavoriteRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FavoriteRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *FavoriteRepository_Expecter) Delete(ctx interface{}, id interface{}) *FavoriteRepository_Delete_Call {
	return &FavoriteRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *FavoriteRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *FavoriteRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FavoriteRepository_Delete_Call) Return(err error) *FavoriteRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FavoriteRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *FavoriteRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllByConnectionID provides a mock function for the type FavoriteRepository
func (_mock *FavoriteRepository) FindAllByConnectionID(ctx context.Context, connectionID int64) ([]*entity.FavoriteComparison, error) {
	ret := _mock.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByConnectionID")
	}

	var r0 []*entity.FavoriteComparison
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*entity.FavoriteComparison, error)); ok {
		return returnFunc(ctx, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*entity.FavoriteComparison); ok {
		r0 = returnFunc(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.FavoriteComparison)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteRepository_FindAllByConnectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByConnectionID'
type FavoriteRepository_FindAllByConnectionID_Call struct {
	*mock.Call
}

// FindAllByConnectionID is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
func (_e *FavoriteRepository_Expecter) FindAllByConnectionID(ctx interface{}, connectionID interface{}) *FavoriteRepository_FindAllByConnectionID_Call {
	return &FavoriteRepository_FindAllByConnectionID_Call{Call: _e.mock.On("FindAllByConnectionID", ctx, connectionID)}
}

func (_c *FavoriteRepository_FindAllByConnectionID_Call) Run(run func(ctx context.Context, connectionID int64)) *FavoriteRepository_FindAllByConnectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FavoriteRepository_FindAllByConnectionID_Call) Return(favoriteComparisons []*entity.FavoriteComparison, err error) *FavoriteRepository_FindAllByConnectionID_Call {
	_c.Call.Return(favoriteComparisons, err)
	return _c
}

func (_c *FavoriteRepository_FindAllByConnectionID_Call) RunAndReturn(run func(ctx context.Context, connectionID int64) ([]*entity.FavoriteComparison, error)) *FavoriteRepository_FindAllByConnectionID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type FavoriteRepository
func (_mock *FavoriteRepository) FindByID(ctx context.Context, id int64) (*entity.FavoriteComparison, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.FavoriteComparison
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.FavoriteComparison, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.FavoriteComparison); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.FavoriteComparison)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type FavoriteRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *FavoriteRepository_Expecter) FindByID(ctx interface{}, id interface{}) *FavoriteRepository_FindByID_Call {
	return &FavoriteRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *FavoriteRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *FavoriteRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FavoriteRepository_FindByID_Call) Return(favoriteComparison *entity.FavoriteComparison, err error) *FavoriteRepository_FindByID_Call {
	_c.Call.Return(favoriteComparison, err)
	return _c
}

func (_c *FavoriteRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.FavoriteComparison, error)) *FavoriteRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}
