// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryHistoryRepository creates a new instance of QueryHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryHistoryRepository {
	mock := &QueryHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryHistoryRepository is an autogenerated mock type for the QueryHistoryRepository type
type QueryHistoryRepository struct {
	mock.Mock
}

type QueryHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryHistoryRepository) EXPECT() *QueryHistoryRepository_Expecter {
	return &QueryHistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type QueryHistoryRepository
func (_mock *QueryHistoryRepository) Create(ctx context.Context, history *entity.QueryHistory) error {
	ret := _mock.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.QueryHistory) error); ok {
		r0 = returnFunc(ctx, history)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueryHistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type QueryHistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *entity.QueryHistory
func (_e *QueryHistoryRepository_Expecter) Create(ctx interface{}, history interface{}) *QueryHistoryRepository_Create_Call {
	return &QueryHistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *QueryHistoryRepository_Create_Call) Run(run func(ctx context.Context, history *entity.QueryHistory)) *QueryHistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.QueryHistory
		if args[1] != nil {
			arg1 = args[1].(*entity.QueryHistory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QueryHistoryRepository_Create_Call) Return(err error) *QueryHistoryRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueryHistoryRepository_Create_Call) RunAndReturn(run func(ctx context.Context, history *entity.QueryHistory) error) *QueryHistoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByConnectionID provides a mock function for the type QueryHistoryRepository
func (_mock *QueryHistoryRepository) FindByConnectionID(ctx context.Context, connectionID int64, limit int) ([]*entity.QueryHistory, error) {
	ret := _mock.Called(ctx, connectionID, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByConnectionID")
	}

	var r0 []*entity.QueryHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]*entity.QueryHistory, error)); ok {
		return returnFunc(ctx, connectionID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []*entity.QueryHistory); ok {
		r0 = returnFunc(ctx, connectionID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.QueryHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, connectionID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// QueryHistoryRepository_FindByConnectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByConnectionID'
type QueryHistoryRepository_FindByConnectionID_Call struct {
	*mock.Call
}

// FindByConnectionID is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
//   - limit int
func (_e *QueryHistoryRepository_Expecter) FindByConnectionID(ctx interface{}, connectionID interface{}, limit interface{}) *QueryHistoryRepository_FindByConnectionID_Call {
	return &QueryHistoryRepository_FindByConnectionID_Call{Call: _e.mock.On("FindByConnectionID", ctx, connectionID, limit)}
}

func (_c *QueryHistoryRepository_FindByConnectionID_Call) Run(run func(ctx context.Context, connectionID int64, limit int)) *QueryHistoryRepository_FindByConnectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QueryHistoryRepository_FindByConnectionID_Call) Return(queryHistorys []*entity.QueryHistory, err error) *QueryHistoryRepository_FindByConnectionID_Call {
	_c.Call.Return(queryHistorys, err)
	return _c
}

func (_c *QueryHistoryRepository_FindByConnectionID_Call) RunAndReturn(run func(ctx context.Context, connectionID int64, limit int) ([]*entity.QueryHistory, error)) *QueryHistoryRepository_FindByConnectionID_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type QueryHistoryRepository
func (_mock *QueryHistoryRepository) Prune(ctx context.Context, connectionID int64, maxLimit int) error {
	ret := _mock.Called(ctx, connectionID, maxLimit)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) error); ok {
		r0 = returnFunc(ctx, connectionID, maxLimit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// QueryHistoryRepository_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type QueryHistoryRepository_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
//   - maxLimit int
func (_e *QueryHistoryRepository_Expecter) Prune(ctx interface{}, connectionID interface{}, maxLimit interface{}) *QueryHistoryRepository_Prune_Call {
	return &QueryHistoryRepository_Prune_Call{Call: _e.mock.On("Prune", ctx, connectionID, maxLimit)}
}

func (_c *QueryHistoryRepository_Prune_Call) Run(run func(ctx context.Context, connectionID int64, maxLimit int)) *QueryHistoryRepository_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *QueryHistoryRepository_Prune_Call) Return(err error) *QueryHistoryRepository_Prune_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *QueryHistoryRepository_Prune_Call) RunAndReturn(run func(ctx context.Context, connectionID int64, maxLimit int) error) *QueryHistoryRepository_Prune_Call {
	_c.Call.Return(run)
	return _c
}
