// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewReportUsecase creates a new instance of ReportUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportUsecase {
	mock := &ReportUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReportUsecase is an autogenerated mock type for the ReportUsecase type
type ReportUsecase struct {
	mock.Mock
}

type ReportUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportUsecase) EXPECT() *ReportUsecase_Expecter {
	return &ReportUsecase_Expecter{mock: &_m.Mock}
}

// GetTopSlowQueries provides a mock function for the type ReportUsecase
func (_mock *ReportUsecase) GetTopSlowQueries(ctx context.Context, connectionID int64, queryKind string, forceRefresh bool) ([]*entity.SlowQueryReport, *time.Time, error) {
	ret := _mock.Called(ctx, connectionID, queryKind, forceRefresh)

	if len(ret) == 0 {
		panic("no return value specified for GetTopSlowQueries")
	}

	var r0 []*entity.SlowQueryReport
	var r1 *time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, bool) ([]*entity.SlowQueryReport, *time.Time, error)); ok {
		return returnFunc(ctx, connectionID, queryKind, forceRefresh)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, bool) []*entity.SlowQueryReport); ok {
		r0 = returnFunc(ctx, connectionID, queryKind, forceRefresh)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SlowQueryReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, bool) *time.Time); ok {
		r1 = returnFunc(ctx, connectionID, queryKind, forceRefresh)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*time.Time)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int64, string, bool) error); ok {
		r2 = returnFunc(ctx, connectionID, queryKind, forceRefresh)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ReportUsecase_GetTopSlowQueries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopSlowQueries'
type ReportUsecase_GetTopSlowQueries_Call struct {
	*mock.Call
}

// GetTopSlowQueries is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
//   - queryKind string
//   - forceRefresh bool
func (_e *ReportUsecase_Expecter) GetTopSlowQueries(ctx interface{}, connectionID interface{}, queryKind interface{}, forceRefresh interface{}) *ReportUsecase_GetTopSlowQueries_Call {
	return &ReportUsecase_GetTopSlowQueries_Call{Call: _e.mock.On("GetTopSlowQueries", ctx, connectionID, queryKind, forceRefresh)}
}

func (_c *ReportUsecase_GetTopSlowQueries_Call) Run(run func(ctx context.Context, connectionID int64, queryKind string, forceRefresh bool)) *ReportUsecase_GetTopSlowQueries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ReportUsecase_GetTopSlowQueries_Call) Return(slowQueryReports []*entity.SlowQueryReport, time1 *time.Time, err error) *ReportUsecase_GetTopSlowQueries_Call {
	_c.Call.Return(slowQueryReports, time1, err)
	return _c
}

func (_c *ReportUsecase_GetTopSlowQueries_Call) RunAndReturn(run func(ctx context.Context, connectionID int64, queryKind string, forceRefresh bool) ([]*entity.SlowQueryReport, *time.Time, error)) *ReportUsecase_GetTopSlowQueries_Call {
	_c.Call.Return(run)
	return _c
}
