// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/rahmatrdn/go-ch-manager/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

// GetSlowQueryReports provides a mock function for the type ReportRepository
func (_mock *ReportRepository) GetSlowQueryReports(ctx context.Context, connectionID int64) ([]*entity.SlowQueryReport, error) {
	ret := _mock.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSlowQueryReports")
	}

	var r0 []*entity.SlowQueryReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*entity.SlowQueryReport, error)); ok {
		return returnFunc(ctx, connectionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*entity.SlowQueryReport); ok {
		r0 = returnFunc(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.SlowQueryReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ReportRepository_GetSlowQueryReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSlowQueryReports'
type ReportRepository_GetSlowQueryReports_Call struct {
	*mock.Call
}

// GetSlowQueryReports is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
func (_e *ReportRepository_Expecter) GetSlowQueryReports(ctx interface{}, connectionID interface{}) *ReportRepository_GetSlowQueryReports_Call {
	return &ReportRepository_GetSlowQueryReports_Call{Call: _e.mock.On("GetSlowQueryReports", ctx, connectionID)}
}

func (_c *ReportRepository_GetSlowQueryReports_Call) Run(run func(ctx context.Context, connectionID int64)) *ReportRepository_GetSlowQueryReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ReportRepository_GetSlowQueryReports_Call) Return(slowQueryReports []*entity.SlowQueryReport, err error) *ReportRepository_GetSlowQueryReports_Call {
	_c.Call.Return(slowQueryReports, err)
	return _c
}

func (_c *ReportRepository_GetSlowQueryReports_Call) RunAndReturn(run func(ctx context.Context, connectionID int64) ([]*entity.SlowQueryReport, error)) *ReportRepository_GetSlowQueryReports_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSlowQueryReports provides a mock function for the type ReportRepository
func (_mock *ReportRepository) SaveSlowQueryReports(ctx context.Context, connectionID int64, reports []*entity.SlowQueryReport) error {
	ret := _mock.Called(ctx, connectionID, reports)

	if len(ret) == 0 {
		panic("no return value specified for SaveSlowQueryReports")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, []*entity.SlowQueryReport) error); ok {
		r0 = returnFunc(ctx, connectionID, reports)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ReportRepository_SaveSlowQueryReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSlowQueryReports'
type ReportRepository_SaveSlowQueryReports_Call struct {
	*mock.Call
}

// SaveSlowQueryReports is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int64
//   - reports []*entity.SlowQueryReport
func (_e *ReportRepository_Expecter) SaveSlowQueryReports(ctx interface{}, connectionID interface{}, reports interface{}) *ReportRepository_SaveSlowQueryReports_Call {
	return &ReportRepository_SaveSlowQueryReports_Call{Call: _e.mock.On("SaveSlowQueryReports", ctx, connectionID, reports)}
}

func (_c *ReportRepository_SaveSlowQueryReports_Call) Run(run func(ctx context.Context, connectionID int64, reports []*entity.SlowQueryReport)) *ReportRepository_SaveSlowQueryReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []*entity.SlowQueryReport
		if args[2] != nil {
			arg2 = args[2].([]*entity.SlowQueryReport)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ReportRepository_SaveSlowQueryReports_Call) Return(err error) *ReportRepository_SaveSlowQueryReports_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ReportRepository_SaveSlowQueryReports_Call) RunAndReturn(run func(ctx context.Context, connectionID int64, reports []*entity.SlowQueryReport) error) *ReportRepository_SaveSlowQueryReports_Call {
	_c.Call.Return(run)
	return _c
}
